name: swarmcg
channels:
  - conda-forge
dependencies:
  - cycler=0.10.0
  - dscribe=0.4.0 # 0.3.5 available for linux
  - matplotlib=3.2.0 # 3.2.1 available
  - mdanalysis>=1.0.0
  - mypy=0.770
  - numpy=1.19.1
  - pandas=1.0.1
  - pip
  - pybind11=2.4.3 # 2.5.0 available
  - pyemd=0.5.1
  - pylint=2.4.4
  - pytest=5.4.1
  - pytest-runner=5.2
  - python=3.7.6
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - setuptools
  - wheel
  - pip:
      - fst-pso
